# Generated by Django 3.1.2 on 2020-11-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogloh', '0002_auto_20201103_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
