# Generated by Django 3.1.2 on 2020-11-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogloh', '0003_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Texto',
            field=models.TextField(null=True),
        ),
    ]
