# Generated by Django 3.1.2 on 2020-11-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogloh', '0004_auto_20201103_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Texto',
            new_name='conteudo',
        ),
    ]
