# Generated by Django 3.1.3 on 2020-11-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogloh', '0007_auto_20201115_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
    ]
