# Generated by Django 3.1.3 on 2020-11-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogloh', '0009_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=250, null=True, verbose_name='Título'),
        ),
    ]
