# Generated by Django 3.1.3 on 2020-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogloh', '0011_auto_20201115_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
