# Generated by Django 3.1.3 on 2020-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogloh', '0012_post_criado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(related_name='get_posts', to='blogloh.Category'),
        ),
    ]
