# Generated by Django 3.1.3 on 2020-11-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogloh', '0013_auto_20201117_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
